ALTER TYPE "fakultas" ADD VALUE IF NOT EXISTS 'HUKUM';
ALTER TYPE "fakultas" ADD VALUE IF NOT EXISTS 'EKONOMI_DAN_BISNIS';
ALTER TYPE "fakultas" ADD VALUE IF NOT EXISTS 'ILMU_BUDAYA';
ALTER TYPE "fakultas" ADD VALUE IF NOT EXISTS 'ILMU_SOSIAL_DAN_POLITIK';
