
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ScheduledWhatsApp` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model ScheduledWhatsApp
 * 
 */
export type ScheduledWhatsAppModel = runtime.Types.Result.DefaultSelection<Prisma.$ScheduledWhatsAppPayload>

export type AggregateScheduledWhatsApp = {
  _count: ScheduledWhatsAppCountAggregateOutputType | null
  _min: ScheduledWhatsAppMinAggregateOutputType | null
  _max: ScheduledWhatsAppMaxAggregateOutputType | null
}

export type ScheduledWhatsAppMinAggregateOutputType = {
  id: string | null
  message: string | null
  scheduledAt: Date | null
  isSent: boolean | null
  sentAt: Date | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type ScheduledWhatsAppMaxAggregateOutputType = {
  id: string | null
  message: string | null
  scheduledAt: Date | null
  isSent: boolean | null
  sentAt: Date | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type ScheduledWhatsAppCountAggregateOutputType = {
  id: number
  message: number
  scheduledAt: number
  isSent: number
  sentAt: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type ScheduledWhatsAppMinAggregateInputType = {
  id?: true
  message?: true
  scheduledAt?: true
  isSent?: true
  sentAt?: true
  createdAt?: true
  updatedAt?: true
}

export type ScheduledWhatsAppMaxAggregateInputType = {
  id?: true
  message?: true
  scheduledAt?: true
  isSent?: true
  sentAt?: true
  createdAt?: true
  updatedAt?: true
}

export type ScheduledWhatsAppCountAggregateInputType = {
  id?: true
  message?: true
  scheduledAt?: true
  isSent?: true
  sentAt?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type ScheduledWhatsAppAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ScheduledWhatsApp to aggregate.
   */
  where?: Prisma.ScheduledWhatsAppWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ScheduledWhatsApps to fetch.
   */
  orderBy?: Prisma.ScheduledWhatsAppOrderByWithRelationInput | Prisma.ScheduledWhatsAppOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ScheduledWhatsAppWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ScheduledWhatsApps from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ScheduledWhatsApps.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ScheduledWhatsApps
  **/
  _count?: true | ScheduledWhatsAppCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ScheduledWhatsAppMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ScheduledWhatsAppMaxAggregateInputType
}

export type GetScheduledWhatsAppAggregateType<T extends ScheduledWhatsAppAggregateArgs> = {
      [P in keyof T & keyof AggregateScheduledWhatsApp]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateScheduledWhatsApp[P]>
    : Prisma.GetScalarType<T[P], AggregateScheduledWhatsApp[P]>
}




export type ScheduledWhatsAppGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ScheduledWhatsAppWhereInput
  orderBy?: Prisma.ScheduledWhatsAppOrderByWithAggregationInput | Prisma.ScheduledWhatsAppOrderByWithAggregationInput[]
  by: Prisma.ScheduledWhatsAppScalarFieldEnum[] | Prisma.ScheduledWhatsAppScalarFieldEnum
  having?: Prisma.ScheduledWhatsAppScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ScheduledWhatsAppCountAggregateInputType | true
  _min?: ScheduledWhatsAppMinAggregateInputType
  _max?: ScheduledWhatsAppMaxAggregateInputType
}

export type ScheduledWhatsAppGroupByOutputType = {
  id: string
  message: string
  scheduledAt: Date
  isSent: boolean
  sentAt: Date | null
  createdAt: Date
  updatedAt: Date
  _count: ScheduledWhatsAppCountAggregateOutputType | null
  _min: ScheduledWhatsAppMinAggregateOutputType | null
  _max: ScheduledWhatsAppMaxAggregateOutputType | null
}

type GetScheduledWhatsAppGroupByPayload<T extends ScheduledWhatsAppGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ScheduledWhatsAppGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ScheduledWhatsAppGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ScheduledWhatsAppGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ScheduledWhatsAppGroupByOutputType[P]>
      }
    >
  >



export type ScheduledWhatsAppWhereInput = {
  AND?: Prisma.ScheduledWhatsAppWhereInput | Prisma.ScheduledWhatsAppWhereInput[]
  OR?: Prisma.ScheduledWhatsAppWhereInput[]
  NOT?: Prisma.ScheduledWhatsAppWhereInput | Prisma.ScheduledWhatsAppWhereInput[]
  id?: Prisma.StringFilter<"ScheduledWhatsApp"> | string
  message?: Prisma.StringFilter<"ScheduledWhatsApp"> | string
  scheduledAt?: Prisma.DateTimeFilter<"ScheduledWhatsApp"> | Date | string
  isSent?: Prisma.BoolFilter<"ScheduledWhatsApp"> | boolean
  sentAt?: Prisma.DateTimeNullableFilter<"ScheduledWhatsApp"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"ScheduledWhatsApp"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"ScheduledWhatsApp"> | Date | string
}

export type ScheduledWhatsAppOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  message?: Prisma.SortOrder
  scheduledAt?: Prisma.SortOrder
  isSent?: Prisma.SortOrder
  sentAt?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ScheduledWhatsAppWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.ScheduledWhatsAppWhereInput | Prisma.ScheduledWhatsAppWhereInput[]
  OR?: Prisma.ScheduledWhatsAppWhereInput[]
  NOT?: Prisma.ScheduledWhatsAppWhereInput | Prisma.ScheduledWhatsAppWhereInput[]
  message?: Prisma.StringFilter<"ScheduledWhatsApp"> | string
  scheduledAt?: Prisma.DateTimeFilter<"ScheduledWhatsApp"> | Date | string
  isSent?: Prisma.BoolFilter<"ScheduledWhatsApp"> | boolean
  sentAt?: Prisma.DateTimeNullableFilter<"ScheduledWhatsApp"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"ScheduledWhatsApp"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"ScheduledWhatsApp"> | Date | string
}, "id">

export type ScheduledWhatsAppOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  message?: Prisma.SortOrder
  scheduledAt?: Prisma.SortOrder
  isSent?: Prisma.SortOrder
  sentAt?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.ScheduledWhatsAppCountOrderByAggregateInput
  _max?: Prisma.ScheduledWhatsAppMaxOrderByAggregateInput
  _min?: Prisma.ScheduledWhatsAppMinOrderByAggregateInput
}

export type ScheduledWhatsAppScalarWhereWithAggregatesInput = {
  AND?: Prisma.ScheduledWhatsAppScalarWhereWithAggregatesInput | Prisma.ScheduledWhatsAppScalarWhereWithAggregatesInput[]
  OR?: Prisma.ScheduledWhatsAppScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ScheduledWhatsAppScalarWhereWithAggregatesInput | Prisma.ScheduledWhatsAppScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"ScheduledWhatsApp"> | string
  message?: Prisma.StringWithAggregatesFilter<"ScheduledWhatsApp"> | string
  scheduledAt?: Prisma.DateTimeWithAggregatesFilter<"ScheduledWhatsApp"> | Date | string
  isSent?: Prisma.BoolWithAggregatesFilter<"ScheduledWhatsApp"> | boolean
  sentAt?: Prisma.DateTimeNullableWithAggregatesFilter<"ScheduledWhatsApp"> | Date | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"ScheduledWhatsApp"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"ScheduledWhatsApp"> | Date | string
}

export type ScheduledWhatsAppCreateInput = {
  id?: string
  message: string
  scheduledAt: Date | string
  isSent?: boolean
  sentAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ScheduledWhatsAppUncheckedCreateInput = {
  id?: string
  message: string
  scheduledAt: Date | string
  isSent?: boolean
  sentAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ScheduledWhatsAppUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  message?: Prisma.StringFieldUpdateOperationsInput | string
  scheduledAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  isSent?: Prisma.BoolFieldUpdateOperationsInput | boolean
  sentAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ScheduledWhatsAppUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  message?: Prisma.StringFieldUpdateOperationsInput | string
  scheduledAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  isSent?: Prisma.BoolFieldUpdateOperationsInput | boolean
  sentAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ScheduledWhatsAppCreateManyInput = {
  id?: string
  message: string
  scheduledAt: Date | string
  isSent?: boolean
  sentAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ScheduledWhatsAppUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  message?: Prisma.StringFieldUpdateOperationsInput | string
  scheduledAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  isSent?: Prisma.BoolFieldUpdateOperationsInput | boolean
  sentAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ScheduledWhatsAppUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  message?: Prisma.StringFieldUpdateOperationsInput | string
  scheduledAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  isSent?: Prisma.BoolFieldUpdateOperationsInput | boolean
  sentAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ScheduledWhatsAppCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  message?: Prisma.SortOrder
  scheduledAt?: Prisma.SortOrder
  isSent?: Prisma.SortOrder
  sentAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ScheduledWhatsAppMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  message?: Prisma.SortOrder
  scheduledAt?: Prisma.SortOrder
  isSent?: Prisma.SortOrder
  sentAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ScheduledWhatsAppMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  message?: Prisma.SortOrder
  scheduledAt?: Prisma.SortOrder
  isSent?: Prisma.SortOrder
  sentAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}



export type ScheduledWhatsAppSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  message?: boolean
  scheduledAt?: boolean
  isSent?: boolean
  sentAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["scheduledWhatsApp"]>

export type ScheduledWhatsAppSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  message?: boolean
  scheduledAt?: boolean
  isSent?: boolean
  sentAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["scheduledWhatsApp"]>

export type ScheduledWhatsAppSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  message?: boolean
  scheduledAt?: boolean
  isSent?: boolean
  sentAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["scheduledWhatsApp"]>

export type ScheduledWhatsAppSelectScalar = {
  id?: boolean
  message?: boolean
  scheduledAt?: boolean
  isSent?: boolean
  sentAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type ScheduledWhatsAppOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "message" | "scheduledAt" | "isSent" | "sentAt" | "createdAt" | "updatedAt", ExtArgs["result"]["scheduledWhatsApp"]>

export type $ScheduledWhatsAppPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ScheduledWhatsApp"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    message: string
    scheduledAt: Date
    isSent: boolean
    sentAt: Date | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["scheduledWhatsApp"]>
  composites: {}
}

export type ScheduledWhatsAppGetPayload<S extends boolean | null | undefined | ScheduledWhatsAppDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ScheduledWhatsAppPayload, S>

export type ScheduledWhatsAppCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ScheduledWhatsAppFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ScheduledWhatsAppCountAggregateInputType | true
  }

export interface ScheduledWhatsAppDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ScheduledWhatsApp'], meta: { name: 'ScheduledWhatsApp' } }
  /**
   * Find zero or one ScheduledWhatsApp that matches the filter.
   * @param {ScheduledWhatsAppFindUniqueArgs} args - Arguments to find a ScheduledWhatsApp
   * @example
   * // Get one ScheduledWhatsApp
   * const scheduledWhatsApp = await prisma.scheduledWhatsApp.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ScheduledWhatsAppFindUniqueArgs>(args: Prisma.SelectSubset<T, ScheduledWhatsAppFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ScheduledWhatsAppClient<runtime.Types.Result.GetResult<Prisma.$ScheduledWhatsAppPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ScheduledWhatsApp that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ScheduledWhatsAppFindUniqueOrThrowArgs} args - Arguments to find a ScheduledWhatsApp
   * @example
   * // Get one ScheduledWhatsApp
   * const scheduledWhatsApp = await prisma.scheduledWhatsApp.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ScheduledWhatsAppFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ScheduledWhatsAppFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ScheduledWhatsAppClient<runtime.Types.Result.GetResult<Prisma.$ScheduledWhatsAppPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ScheduledWhatsApp that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ScheduledWhatsAppFindFirstArgs} args - Arguments to find a ScheduledWhatsApp
   * @example
   * // Get one ScheduledWhatsApp
   * const scheduledWhatsApp = await prisma.scheduledWhatsApp.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ScheduledWhatsAppFindFirstArgs>(args?: Prisma.SelectSubset<T, ScheduledWhatsAppFindFirstArgs<ExtArgs>>): Prisma.Prisma__ScheduledWhatsAppClient<runtime.Types.Result.GetResult<Prisma.$ScheduledWhatsAppPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ScheduledWhatsApp that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ScheduledWhatsAppFindFirstOrThrowArgs} args - Arguments to find a ScheduledWhatsApp
   * @example
   * // Get one ScheduledWhatsApp
   * const scheduledWhatsApp = await prisma.scheduledWhatsApp.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ScheduledWhatsAppFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ScheduledWhatsAppFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ScheduledWhatsAppClient<runtime.Types.Result.GetResult<Prisma.$ScheduledWhatsAppPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ScheduledWhatsApps that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ScheduledWhatsAppFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ScheduledWhatsApps
   * const scheduledWhatsApps = await prisma.scheduledWhatsApp.findMany()
   * 
   * // Get first 10 ScheduledWhatsApps
   * const scheduledWhatsApps = await prisma.scheduledWhatsApp.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const scheduledWhatsAppWithIdOnly = await prisma.scheduledWhatsApp.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ScheduledWhatsAppFindManyArgs>(args?: Prisma.SelectSubset<T, ScheduledWhatsAppFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ScheduledWhatsAppPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ScheduledWhatsApp.
   * @param {ScheduledWhatsAppCreateArgs} args - Arguments to create a ScheduledWhatsApp.
   * @example
   * // Create one ScheduledWhatsApp
   * const ScheduledWhatsApp = await prisma.scheduledWhatsApp.create({
   *   data: {
   *     // ... data to create a ScheduledWhatsApp
   *   }
   * })
   * 
   */
  create<T extends ScheduledWhatsAppCreateArgs>(args: Prisma.SelectSubset<T, ScheduledWhatsAppCreateArgs<ExtArgs>>): Prisma.Prisma__ScheduledWhatsAppClient<runtime.Types.Result.GetResult<Prisma.$ScheduledWhatsAppPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ScheduledWhatsApps.
   * @param {ScheduledWhatsAppCreateManyArgs} args - Arguments to create many ScheduledWhatsApps.
   * @example
   * // Create many ScheduledWhatsApps
   * const scheduledWhatsApp = await prisma.scheduledWhatsApp.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ScheduledWhatsAppCreateManyArgs>(args?: Prisma.SelectSubset<T, ScheduledWhatsAppCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many ScheduledWhatsApps and returns the data saved in the database.
   * @param {ScheduledWhatsAppCreateManyAndReturnArgs} args - Arguments to create many ScheduledWhatsApps.
   * @example
   * // Create many ScheduledWhatsApps
   * const scheduledWhatsApp = await prisma.scheduledWhatsApp.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many ScheduledWhatsApps and only return the `id`
   * const scheduledWhatsAppWithIdOnly = await prisma.scheduledWhatsApp.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ScheduledWhatsAppCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ScheduledWhatsAppCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ScheduledWhatsAppPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a ScheduledWhatsApp.
   * @param {ScheduledWhatsAppDeleteArgs} args - Arguments to delete one ScheduledWhatsApp.
   * @example
   * // Delete one ScheduledWhatsApp
   * const ScheduledWhatsApp = await prisma.scheduledWhatsApp.delete({
   *   where: {
   *     // ... filter to delete one ScheduledWhatsApp
   *   }
   * })
   * 
   */
  delete<T extends ScheduledWhatsAppDeleteArgs>(args: Prisma.SelectSubset<T, ScheduledWhatsAppDeleteArgs<ExtArgs>>): Prisma.Prisma__ScheduledWhatsAppClient<runtime.Types.Result.GetResult<Prisma.$ScheduledWhatsAppPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ScheduledWhatsApp.
   * @param {ScheduledWhatsAppUpdateArgs} args - Arguments to update one ScheduledWhatsApp.
   * @example
   * // Update one ScheduledWhatsApp
   * const scheduledWhatsApp = await prisma.scheduledWhatsApp.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ScheduledWhatsAppUpdateArgs>(args: Prisma.SelectSubset<T, ScheduledWhatsAppUpdateArgs<ExtArgs>>): Prisma.Prisma__ScheduledWhatsAppClient<runtime.Types.Result.GetResult<Prisma.$ScheduledWhatsAppPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ScheduledWhatsApps.
   * @param {ScheduledWhatsAppDeleteManyArgs} args - Arguments to filter ScheduledWhatsApps to delete.
   * @example
   * // Delete a few ScheduledWhatsApps
   * const { count } = await prisma.scheduledWhatsApp.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ScheduledWhatsAppDeleteManyArgs>(args?: Prisma.SelectSubset<T, ScheduledWhatsAppDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ScheduledWhatsApps.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ScheduledWhatsAppUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ScheduledWhatsApps
   * const scheduledWhatsApp = await prisma.scheduledWhatsApp.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ScheduledWhatsAppUpdateManyArgs>(args: Prisma.SelectSubset<T, ScheduledWhatsAppUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ScheduledWhatsApps and returns the data updated in the database.
   * @param {ScheduledWhatsAppUpdateManyAndReturnArgs} args - Arguments to update many ScheduledWhatsApps.
   * @example
   * // Update many ScheduledWhatsApps
   * const scheduledWhatsApp = await prisma.scheduledWhatsApp.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more ScheduledWhatsApps and only return the `id`
   * const scheduledWhatsAppWithIdOnly = await prisma.scheduledWhatsApp.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ScheduledWhatsAppUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ScheduledWhatsAppUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ScheduledWhatsAppPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one ScheduledWhatsApp.
   * @param {ScheduledWhatsAppUpsertArgs} args - Arguments to update or create a ScheduledWhatsApp.
   * @example
   * // Update or create a ScheduledWhatsApp
   * const scheduledWhatsApp = await prisma.scheduledWhatsApp.upsert({
   *   create: {
   *     // ... data to create a ScheduledWhatsApp
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ScheduledWhatsApp we want to update
   *   }
   * })
   */
  upsert<T extends ScheduledWhatsAppUpsertArgs>(args: Prisma.SelectSubset<T, ScheduledWhatsAppUpsertArgs<ExtArgs>>): Prisma.Prisma__ScheduledWhatsAppClient<runtime.Types.Result.GetResult<Prisma.$ScheduledWhatsAppPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ScheduledWhatsApps.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ScheduledWhatsAppCountArgs} args - Arguments to filter ScheduledWhatsApps to count.
   * @example
   * // Count the number of ScheduledWhatsApps
   * const count = await prisma.scheduledWhatsApp.count({
   *   where: {
   *     // ... the filter for the ScheduledWhatsApps we want to count
   *   }
   * })
  **/
  count<T extends ScheduledWhatsAppCountArgs>(
    args?: Prisma.Subset<T, ScheduledWhatsAppCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ScheduledWhatsAppCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ScheduledWhatsApp.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ScheduledWhatsAppAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ScheduledWhatsAppAggregateArgs>(args: Prisma.Subset<T, ScheduledWhatsAppAggregateArgs>): Prisma.PrismaPromise<GetScheduledWhatsAppAggregateType<T>>

  /**
   * Group by ScheduledWhatsApp.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ScheduledWhatsAppGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ScheduledWhatsAppGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ScheduledWhatsAppGroupByArgs['orderBy'] }
      : { orderBy?: ScheduledWhatsAppGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ScheduledWhatsAppGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetScheduledWhatsAppGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ScheduledWhatsApp model
 */
readonly fields: ScheduledWhatsAppFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ScheduledWhatsApp.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ScheduledWhatsAppClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ScheduledWhatsApp model
 */
export interface ScheduledWhatsAppFieldRefs {
  readonly id: Prisma.FieldRef<"ScheduledWhatsApp", 'String'>
  readonly message: Prisma.FieldRef<"ScheduledWhatsApp", 'String'>
  readonly scheduledAt: Prisma.FieldRef<"ScheduledWhatsApp", 'DateTime'>
  readonly isSent: Prisma.FieldRef<"ScheduledWhatsApp", 'Boolean'>
  readonly sentAt: Prisma.FieldRef<"ScheduledWhatsApp", 'DateTime'>
  readonly createdAt: Prisma.FieldRef<"ScheduledWhatsApp", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"ScheduledWhatsApp", 'DateTime'>
}
    

// Custom InputTypes
/**
 * ScheduledWhatsApp findUnique
 */
export type ScheduledWhatsAppFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ScheduledWhatsApp
   */
  select?: Prisma.ScheduledWhatsAppSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ScheduledWhatsApp
   */
  omit?: Prisma.ScheduledWhatsAppOmit<ExtArgs> | null
  /**
   * Filter, which ScheduledWhatsApp to fetch.
   */
  where: Prisma.ScheduledWhatsAppWhereUniqueInput
}

/**
 * ScheduledWhatsApp findUniqueOrThrow
 */
export type ScheduledWhatsAppFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ScheduledWhatsApp
   */
  select?: Prisma.ScheduledWhatsAppSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ScheduledWhatsApp
   */
  omit?: Prisma.ScheduledWhatsAppOmit<ExtArgs> | null
  /**
   * Filter, which ScheduledWhatsApp to fetch.
   */
  where: Prisma.ScheduledWhatsAppWhereUniqueInput
}

/**
 * ScheduledWhatsApp findFirst
 */
export type ScheduledWhatsAppFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ScheduledWhatsApp
   */
  select?: Prisma.ScheduledWhatsAppSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ScheduledWhatsApp
   */
  omit?: Prisma.ScheduledWhatsAppOmit<ExtArgs> | null
  /**
   * Filter, which ScheduledWhatsApp to fetch.
   */
  where?: Prisma.ScheduledWhatsAppWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ScheduledWhatsApps to fetch.
   */
  orderBy?: Prisma.ScheduledWhatsAppOrderByWithRelationInput | Prisma.ScheduledWhatsAppOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ScheduledWhatsApps.
   */
  cursor?: Prisma.ScheduledWhatsAppWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ScheduledWhatsApps from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ScheduledWhatsApps.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ScheduledWhatsApps.
   */
  distinct?: Prisma.ScheduledWhatsAppScalarFieldEnum | Prisma.ScheduledWhatsAppScalarFieldEnum[]
}

/**
 * ScheduledWhatsApp findFirstOrThrow
 */
export type ScheduledWhatsAppFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ScheduledWhatsApp
   */
  select?: Prisma.ScheduledWhatsAppSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ScheduledWhatsApp
   */
  omit?: Prisma.ScheduledWhatsAppOmit<ExtArgs> | null
  /**
   * Filter, which ScheduledWhatsApp to fetch.
   */
  where?: Prisma.ScheduledWhatsAppWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ScheduledWhatsApps to fetch.
   */
  orderBy?: Prisma.ScheduledWhatsAppOrderByWithRelationInput | Prisma.ScheduledWhatsAppOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ScheduledWhatsApps.
   */
  cursor?: Prisma.ScheduledWhatsAppWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ScheduledWhatsApps from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ScheduledWhatsApps.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ScheduledWhatsApps.
   */
  distinct?: Prisma.ScheduledWhatsAppScalarFieldEnum | Prisma.ScheduledWhatsAppScalarFieldEnum[]
}

/**
 * ScheduledWhatsApp findMany
 */
export type ScheduledWhatsAppFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ScheduledWhatsApp
   */
  select?: Prisma.ScheduledWhatsAppSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ScheduledWhatsApp
   */
  omit?: Prisma.ScheduledWhatsAppOmit<ExtArgs> | null
  /**
   * Filter, which ScheduledWhatsApps to fetch.
   */
  where?: Prisma.ScheduledWhatsAppWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ScheduledWhatsApps to fetch.
   */
  orderBy?: Prisma.ScheduledWhatsAppOrderByWithRelationInput | Prisma.ScheduledWhatsAppOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ScheduledWhatsApps.
   */
  cursor?: Prisma.ScheduledWhatsAppWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ScheduledWhatsApps from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ScheduledWhatsApps.
   */
  skip?: number
  distinct?: Prisma.ScheduledWhatsAppScalarFieldEnum | Prisma.ScheduledWhatsAppScalarFieldEnum[]
}

/**
 * ScheduledWhatsApp create
 */
export type ScheduledWhatsAppCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ScheduledWhatsApp
   */
  select?: Prisma.ScheduledWhatsAppSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ScheduledWhatsApp
   */
  omit?: Prisma.ScheduledWhatsAppOmit<ExtArgs> | null
  /**
   * The data needed to create a ScheduledWhatsApp.
   */
  data: Prisma.XOR<Prisma.ScheduledWhatsAppCreateInput, Prisma.ScheduledWhatsAppUncheckedCreateInput>
}

/**
 * ScheduledWhatsApp createMany
 */
export type ScheduledWhatsAppCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ScheduledWhatsApps.
   */
  data: Prisma.ScheduledWhatsAppCreateManyInput | Prisma.ScheduledWhatsAppCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ScheduledWhatsApp createManyAndReturn
 */
export type ScheduledWhatsAppCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ScheduledWhatsApp
   */
  select?: Prisma.ScheduledWhatsAppSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ScheduledWhatsApp
   */
  omit?: Prisma.ScheduledWhatsAppOmit<ExtArgs> | null
  /**
   * The data used to create many ScheduledWhatsApps.
   */
  data: Prisma.ScheduledWhatsAppCreateManyInput | Prisma.ScheduledWhatsAppCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ScheduledWhatsApp update
 */
export type ScheduledWhatsAppUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ScheduledWhatsApp
   */
  select?: Prisma.ScheduledWhatsAppSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ScheduledWhatsApp
   */
  omit?: Prisma.ScheduledWhatsAppOmit<ExtArgs> | null
  /**
   * The data needed to update a ScheduledWhatsApp.
   */
  data: Prisma.XOR<Prisma.ScheduledWhatsAppUpdateInput, Prisma.ScheduledWhatsAppUncheckedUpdateInput>
  /**
   * Choose, which ScheduledWhatsApp to update.
   */
  where: Prisma.ScheduledWhatsAppWhereUniqueInput
}

/**
 * ScheduledWhatsApp updateMany
 */
export type ScheduledWhatsAppUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ScheduledWhatsApps.
   */
  data: Prisma.XOR<Prisma.ScheduledWhatsAppUpdateManyMutationInput, Prisma.ScheduledWhatsAppUncheckedUpdateManyInput>
  /**
   * Filter which ScheduledWhatsApps to update
   */
  where?: Prisma.ScheduledWhatsAppWhereInput
  /**
   * Limit how many ScheduledWhatsApps to update.
   */
  limit?: number
}

/**
 * ScheduledWhatsApp updateManyAndReturn
 */
export type ScheduledWhatsAppUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ScheduledWhatsApp
   */
  select?: Prisma.ScheduledWhatsAppSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ScheduledWhatsApp
   */
  omit?: Prisma.ScheduledWhatsAppOmit<ExtArgs> | null
  /**
   * The data used to update ScheduledWhatsApps.
   */
  data: Prisma.XOR<Prisma.ScheduledWhatsAppUpdateManyMutationInput, Prisma.ScheduledWhatsAppUncheckedUpdateManyInput>
  /**
   * Filter which ScheduledWhatsApps to update
   */
  where?: Prisma.ScheduledWhatsAppWhereInput
  /**
   * Limit how many ScheduledWhatsApps to update.
   */
  limit?: number
}

/**
 * ScheduledWhatsApp upsert
 */
export type ScheduledWhatsAppUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ScheduledWhatsApp
   */
  select?: Prisma.ScheduledWhatsAppSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ScheduledWhatsApp
   */
  omit?: Prisma.ScheduledWhatsAppOmit<ExtArgs> | null
  /**
   * The filter to search for the ScheduledWhatsApp to update in case it exists.
   */
  where: Prisma.ScheduledWhatsAppWhereUniqueInput
  /**
   * In case the ScheduledWhatsApp found by the `where` argument doesn't exist, create a new ScheduledWhatsApp with this data.
   */
  create: Prisma.XOR<Prisma.ScheduledWhatsAppCreateInput, Prisma.ScheduledWhatsAppUncheckedCreateInput>
  /**
   * In case the ScheduledWhatsApp was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ScheduledWhatsAppUpdateInput, Prisma.ScheduledWhatsAppUncheckedUpdateInput>
}

/**
 * ScheduledWhatsApp delete
 */
export type ScheduledWhatsAppDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ScheduledWhatsApp
   */
  select?: Prisma.ScheduledWhatsAppSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ScheduledWhatsApp
   */
  omit?: Prisma.ScheduledWhatsAppOmit<ExtArgs> | null
  /**
   * Filter which ScheduledWhatsApp to delete.
   */
  where: Prisma.ScheduledWhatsAppWhereUniqueInput
}

/**
 * ScheduledWhatsApp deleteMany
 */
export type ScheduledWhatsAppDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ScheduledWhatsApps to delete
   */
  where?: Prisma.ScheduledWhatsAppWhereInput
  /**
   * Limit how many ScheduledWhatsApps to delete.
   */
  limit?: number
}

/**
 * ScheduledWhatsApp without action
 */
export type ScheduledWhatsAppDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ScheduledWhatsApp
   */
  select?: Prisma.ScheduledWhatsAppSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ScheduledWhatsApp
   */
  omit?: Prisma.ScheduledWhatsAppOmit<ExtArgs> | null
}
